;this file for FamiTone2 library generated by text2data tool

music_music_data:
	.byte 14
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,245,204
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,245,204
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,307,256
	.word @song4ch0,@song4ch1,@song4ch2,@song4ch3,@song4ch4,307,256
	.word @song5ch0,@song5ch1,@song5ch2,@song5ch3,@song5ch4,307,256
	.word @song6ch0,@song6ch1,@song6ch2,@song6ch3,@song6ch4,307,256
	.word @song7ch0,@song7ch1,@song7ch2,@song7ch3,@song7ch4,307,256
	.word @song8ch0,@song8ch1,@song8ch2,@song8ch3,@song8ch4,307,256
	.word @song9ch0,@song9ch1,@song9ch2,@song9ch3,@song9ch4,307,256
	.word @song10ch0,@song10ch1,@song10ch2,@song10ch3,@song10ch4,409,341
	.word @song11ch0,@song11ch1,@song11ch2,@song11ch3,@song11ch4,307,256
	.word @song12ch0,@song12ch1,@song12ch2,@song12ch3,@song12ch4,307,256
	.word @song13ch0,@song13ch1,@song13ch2,@song13ch3,@song13ch4,307,256

@instruments:
	.byte $30 ;instrument $01
	.word @env2,@env0,@env28
	.byte $00
	.byte $b0 ;instrument $05
	.word @env3,@env0,@env29
	.byte $00
	.byte $b0 ;instrument $0d
	.word @env4,@env0,@env0
	.byte $00
	.byte $30 ;instrument $0e
	.word @env5,@env0,@env30
	.byte $00
	.byte $30 ;instrument $0f
	.word @env6,@env0,@env0
	.byte $00
	.byte $30 ;instrument $10
	.word @env4,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $12
	.word @env4,@env0,@env0
	.byte $00
	.byte $70 ;instrument $13
	.word @env5,@env0,@env30
	.byte $00
	.byte $b0 ;instrument $14
	.word @env6,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $15
	.word @env4,@env0,@env0
	.byte $00
	.byte $30 ;instrument $17
	.word @env1,@env0,@env0
	.byte $00
	.byte $30 ;instrument $1e
	.word @env7,@env0,@env0
	.byte $00
	.byte $30 ;instrument $1f
	.word @env8,@env0,@env0
	.byte $00
	.byte $30 ;instrument $22
	.word @env9,@env21,@env0
	.byte $00
	.byte $30 ;instrument $23
	.word @env10,@env0,@env0
	.byte $00
	.byte $30 ;instrument $26
	.word @env11,@env22,@env0
	.byte $00
	.byte $30 ;instrument $28
	.word @env12,@env23,@env0
	.byte $00
	.byte $30 ;instrument $2a
	.word @env13,@env0,@env0
	.byte $00
	.byte $30 ;instrument $2d
	.word @env14,@env24,@env0
	.byte $00
	.byte $b0 ;instrument $2f
	.word @env15,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $30
	.word @env16,@env25,@env0
	.byte $00
	.byte $b0 ;instrument $31
	.word @env17,@env26,@env29
	.byte $00
	.byte $30 ;instrument $32
	.word @env18,@env24,@env0
	.byte $00
	.byte $f0 ;instrument $33
	.word @env19,@env27,@env0
	.byte $00
	.byte $30 ;instrument $34
	.word @env20,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$00,$00
@env2:
	.byte $c3,$00,$00
@env3:
	.byte $cb,$ce,$c9,$c4,$c1,$c0,$00,$05
@env4:
	.byte $c8,$c7,$c6,$c6,$c5,$c5,$c4,$00,$06
@env5:
	.byte $c2,$c4,$c6,$c6,$c7,$c7,$c8,$c7,$c6,$c5,$c5,$c4,$00,$0b
@env6:
	.byte $c2,$c8,$c6,$c5,$c5,$c4,$c4,$00,$06
@env7:
	.byte $cf,$09,$c0,$cf,$c0,$c0,$cf,$c0,$c0,$cf,$c0,$c0,$cf,$c0,$c0,$cf
	.byte $c0,$02,$cf,$c0,$02,$cf,$c0,$00,$16
@env8:
	.byte $c8,$c0,$00,$01
@env9:
	.byte $ca,$c3,$c2,$c1,$c0,$00,$04
@env10:
	.byte $c8,$c7,$c6,$c5,$02,$c4,$02,$c0,$00,$07
@env11:
	.byte $ca,$c8,$c7,$c6,$c6,$c5,$02,$c4,$c4,$c3,$c2,$c0,$00,$0b
@env12:
	.byte $cf,$c8,$c6,$c5,$c4,$c3,$c2,$c2,$c1,$c1,$c0,$00,$0a
@env13:
	.byte $c2,$00,$00
@env14:
	.byte $c8,$c3,$c2,$c2,$c1,$02,$c0,$00,$06
@env15:
	.byte $c4,$c4,$c3,$03,$c2,$00,$04
@env16:
	.byte $c2,$c8,$c6,$c5,$c5,$c4,$11,$c3,$02,$c2,$02,$c1,$03,$c0,$00,$0d
@env17:
	.byte $c7,$c9,$c6,$c2,$c1,$c0,$00,$05
@env18:
	.byte $c4,$c2,$c2,$c1,$c1,$c0,$00,$05
@env19:
	.byte $ca,$c8,$c5,$c3,$c2,$c3,$c4,$c5,$c6,$c7,$c9,$00,$00
@env20:
	.byte $cb,$00,$00
@env21:
	.byte $c0,$c2,$c0,$00,$02
@env22:
	.byte $c0,$c2,$c1,$c1,$c2,$c2,$00,$05
@env23:
	.byte $c0,$c1,$c2,$c3,$00,$03
@env24:
	.byte $c0,$c8,$cb,$cd,$ce,$00,$04
@env25:
	.byte $c5,$00,$00
@env26:
	.byte $c0,$c1,$00,$01
@env27:
	.byte $c0,$c0,$c1,$c2,$c2,$c1,$c0,$c0,$00,$07
@env28:
	.byte $ca,$da,$00,$01
@env29:
	.byte $ff,$00,$00
@env30:
	.byte $c0,$1f,$c1,$c2,$02,$c1,$c0,$00,$02


@song0ch0:
	.byte $fb,$08
@song0ch0loop:
@ref0:
	.byte $9f
@ref1:
	.byte $9f
@ref2:
	.byte $9f
@ref3:
	.byte $9f
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref4:
	.byte $9f
@ref5:
	.byte $9f
@ref6:
	.byte $9f
@ref7:
	.byte $9f
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref8:
	.byte $80,$42,$83,$00,$5c,$83,$00,$42,$42,$42,$5c,$83,$00,$81
@ref9:
	.byte $42,$83,$00,$5c,$83,$00,$42,$42,$42,$5d,$00,$46,$48
@ref10:
	.byte $42,$83,$00,$5c,$83,$00,$42,$42,$42,$5d,$50,$50,$81
@ref11:
	.byte $42,$83,$00,$5c,$83,$00,$42,$42,$42,$5c,$00,$68,$6c,$81
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref12:
	.byte $80,$18,$00,$19,$1c,$00,$1d,$0e,$00,$19,$00,$85
@ref13:
	.byte $18,$00,$19,$1c,$00,$1d,$0e,$00,$19,$00,$85
	.byte $ff,$0b
	.word @ref13
	.byte $ff,$0b
	.word @ref13
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref16:
	.byte $9f
@ref17:
	.byte $9f
@ref18:
	.byte $9f
@ref19:
	.byte $9f
	.byte $fd
	.word @song0ch4loop


@song1ch0:
	.byte $fb,$08
@song1ch0loop:
@ref20:
	.byte $84,$62,$63,$6c,$6d,$62,$63,$6c,$6c,$89
@ref21:
	.byte $62,$63,$6c,$6d,$62,$63,$6c,$6c,$89
	.byte $ff,$09
	.word @ref21
	.byte $ff,$09
	.word @ref21
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@song1ch1loop:
@ref24:
	.byte $a2,$02,$85,$02,$87,$06,$8b
@ref25:
	.byte $02,$8d,$0a,$8d
@ref26:
	.byte $02,$85,$02,$87,$06,$8b
@ref27:
	.byte $02,$8d,$0a,$8d
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@song1ch2loop:
@ref28:
	.byte $84,$6c,$70,$75,$7a,$83,$6d,$75,$7a,$85,$00
@ref29:
	.byte $6c,$70,$75,$7a,$83,$6d,$75,$6c,$85,$00
@ref30:
	.byte $6c,$70,$75,$7a,$83,$6d,$75,$7a,$85,$00
	.byte $ff,$0a
	.word @ref29
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@song1ch3loop:
@ref32:
	.byte $98,$1e,$8f,$21,$20,$87
@ref33:
	.byte $1e,$8f,$21,$20,$87
	.byte $ff,$05
	.word @ref33
	.byte $ff,$05
	.word @ref33
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@song1ch4loop:
@ref36:
	.byte $9f
@ref37:
	.byte $9f
@ref38:
	.byte $9f
@ref39:
	.byte $9f
	.byte $fd
	.word @song1ch4loop


@song2ch0:
	.byte $fb,$02
@song2ch0loop:
@ref40:
	.byte $b0,$24,$83,$00,$24,$83,$00,$2c,$8b,$00,$32,$8b,$00,$36,$8b,$00
@ref41:
	.byte $3a,$83,$00,$36,$8b,$00,$3a,$83,$00,$36,$8b,$00,$32,$8b,$00
@ref42:
	.byte $24,$83,$00,$24,$83,$00,$2c,$8b,$00,$32,$8b,$00,$36,$8b,$00
@ref43:
	.byte $3a,$83,$00,$36,$8b,$00,$3a,$83,$00,$32,$9b,$00
	.byte $ff,$0f
	.word @ref42
	.byte $ff,$0f
	.word @ref41
	.byte $ff,$0f
	.word @ref42
@ref47:
	.byte $32,$83,$00,$2c,$8b,$00,$28,$83,$00,$24,$9b,$00
@ref48:
	.byte $81
	.byte $fd
	.word @song2ch0loop

@song2ch1:
@song2ch1loop:
@ref49:
	.byte $ae,$54,$83,$00,$54,$83,$00,$5c,$8b,$00,$62,$8b,$00,$66,$8b,$00
@ref50:
	.byte $6a,$83,$00,$66,$8b,$00,$6a,$83,$00,$66,$8b,$00,$62,$8b,$00
@ref51:
	.byte $54,$83,$00,$54,$83,$00,$5c,$8b,$00,$62,$8b,$00,$66,$8b,$00
@ref52:
	.byte $6a,$83,$00,$66,$8b,$00,$6a,$83,$00,$62,$9b,$00
	.byte $ff,$0f
	.word @ref51
	.byte $ff,$0f
	.word @ref50
	.byte $ff,$0f
	.word @ref51
@ref56:
	.byte $62,$83,$00,$5c,$8b,$00,$58,$83,$00,$54,$9b,$00
@ref57:
	.byte $81
	.byte $fd
	.word @song2ch1loop

@song2ch2:
@song2ch2loop:
@ref58:
	.byte $94,$0c,$83,$00,$0c,$83,$00,$14,$8b,$00,$1a,$8b,$00,$1e,$8b,$00
@ref59:
	.byte $22,$83,$00,$1e,$8b,$00,$22,$83,$00,$1e,$8b,$00,$1a,$8b,$00
@ref60:
	.byte $0c,$83,$00,$0c,$83,$00,$14,$8b,$00,$1a,$8b,$00,$1e,$8b,$00
@ref61:
	.byte $22,$83,$00,$1e,$8b,$00,$22,$83,$00,$1a,$9b,$00
	.byte $ff,$0f
	.word @ref60
	.byte $ff,$0f
	.word @ref59
	.byte $ff,$0f
	.word @ref60
@ref65:
	.byte $1a,$83,$00,$14,$8b,$00,$10,$83,$00,$0c,$9b,$00
@ref66:
	.byte $81
	.byte $fd
	.word @song2ch2loop

@song2ch3:
@song2ch3loop:
@ref67:
	.byte $ac,$08,$85,$08,$85,$08,$8d,$10,$8d,$08,$8d
@ref68:
	.byte $08,$85,$08,$8d,$08,$85,$08,$8d,$10,$8d
@ref69:
	.byte $08,$85,$08,$85,$08,$8d,$10,$8d,$08,$8d
	.byte $ff,$0a
	.word @ref68
	.byte $ff,$0a
	.word @ref69
	.byte $ff,$0a
	.word @ref68
	.byte $ff,$0a
	.word @ref69
	.byte $ff,$0a
	.word @ref68
@ref75:
	.byte $08
	.byte $fd
	.word @song2ch3loop

@song2ch4:
@song2ch4loop:
@ref76:
	.byte $bf
@ref77:
	.byte $bf
@ref78:
	.byte $bf
@ref79:
	.byte $bf
@ref80:
	.byte $bf
@ref81:
	.byte $bf
@ref82:
	.byte $bf
@ref83:
	.byte $bf
@ref84:
	.byte $81
	.byte $fd
	.word @song2ch4loop


@song3ch0:
	.byte $fb,$06
@song3ch0loop:
@ref85:
	.byte $8f,$90,$6c,$74,$83,$6a,$70,$83,$6c,$87,$00,$d3
	.byte $fd
	.word @song3ch0loop

@song3ch1:
@song3ch1loop:
@ref86:
	.byte $8f,$86,$24,$2c,$83,$22,$28,$83,$24,$87,$00,$d3
	.byte $fd
	.word @song3ch1loop

@song3ch2:
@song3ch2loop:
@ref87:
	.byte $a5,$94,$03,$00,$d3
	.byte $fd
	.word @song3ch2loop

@song3ch3:
@song3ch3loop:
@ref88:
	.byte $82,$14,$a7,$00,$d3
	.byte $fd
	.word @song3ch3loop

@song3ch4:
@song3ch4loop:
@ref89:
	.byte $f9,$85
	.byte $fd
	.word @song3ch4loop


@song4ch0:
	.byte $fb,$08
@ref90:
	.byte $00,$bd
@ref91:
	.byte $bf
@song4ch0loop:
@ref92:
	.byte $92,$42,$85,$50,$85,$57,$51,$57,$50,$99,$00,$85
@ref93:
	.byte $5a,$85,$68,$85,$6f,$69,$6f,$68,$99,$00,$85
@ref94:
	.byte $42,$85,$50,$85,$57,$51,$57,$50,$99,$00,$85
	.byte $ff,$0b
	.word @ref93
@ref96:
	.byte $35,$01,$35,$01,$39,$00,$87,$00,$35,$01,$35,$01,$39,$00,$89
@ref97:
	.byte $4d,$01,$4d,$01,$51,$00,$87,$00,$4d,$01,$4d,$01,$51,$00,$89
	.byte $fd
	.word @song4ch0loop

@song4ch1:
@ref98:
	.byte $a6,$02,$83,$00,$10,$83,$00,$02,$02,$02,$10,$83,$01,$02,$83,$00
	.byte $10,$83,$00,$02,$02,$02,$11,$00,$16,$18
@ref99:
	.byte $0a,$83,$00,$18,$83,$00,$0a,$0a,$0a,$19,$20,$21,$0a,$83,$00,$18
	.byte $83,$00,$0a,$0a,$0a,$18,$00,$0c,$0a,$81
@song4ch1loop:
	.byte $ff,$19
	.word @ref98
	.byte $ff,$1a
	.word @ref99
@ref102:
	.byte $02,$83,$00,$10,$83,$00,$02,$02,$02,$10,$83,$01,$02,$83,$00,$10
	.byte $83,$00,$02,$02,$02,$11,$00,$16,$18
	.byte $ff,$1a
	.word @ref99
	.byte $ff,$19
	.word @ref102
	.byte $ff,$1a
	.word @ref99
	.byte $fd
	.word @song4ch1loop

@song4ch2:
@ref106:
	.byte $bf
@ref107:
	.byte $bf
@song4ch2loop:
@ref108:
	.byte $bf
@ref109:
	.byte $bf
@ref110:
	.byte $bf
@ref111:
	.byte $bf
@ref112:
	.byte $bf
@ref113:
	.byte $bf
	.byte $fd
	.word @song4ch2loop

@song4ch3:
@ref114:
	.byte $80,$18,$00,$19,$1c,$00,$1d,$0e,$00,$19,$00,$85,$18,$00,$19,$1c
	.byte $00,$1d,$0e,$00,$19,$00,$85
@ref115:
	.byte $18,$00,$19,$1c,$00,$1d,$0e,$00,$19,$00,$85,$18,$00,$19,$1c,$00
	.byte $1d,$0e,$00,$19,$00,$85
@song4ch3loop:
	.byte $ff,$16
	.word @ref114
	.byte $ff,$16
	.word @ref115
	.byte $ff,$16
	.word @ref115
	.byte $ff,$16
	.word @ref115
	.byte $ff,$16
	.word @ref115
	.byte $ff,$16
	.word @ref115
	.byte $fd
	.word @song4ch3loop

@song4ch4:
@ref122:
	.byte $bf
@ref123:
	.byte $bf
@song4ch4loop:
@ref124:
	.byte $bf
@ref125:
	.byte $bf
@ref126:
	.byte $bf
@ref127:
	.byte $bf
@ref128:
	.byte $bf
@ref129:
	.byte $bf
	.byte $fd
	.word @song4ch4loop


@song5ch0:
	.byte $fb,$03
@song5ch0loop:
@ref130:
	.byte $90,$52,$85,$01,$55,$58,$89,$01,$6a,$89,$01,$62,$89,$00,$81
@ref131:
	.byte $67,$01,$62,$a5,$00,$8d
@ref132:
	.byte $54,$85,$01,$57,$5a,$89,$01,$6c,$89,$01,$68,$89,$00,$81
@ref133:
	.byte $6d,$01,$68,$a5,$00,$8d
@ref134:
	.byte $52,$85,$01,$55,$58,$89,$01,$6a,$89,$01,$62,$89,$00,$81
@ref135:
	.byte $67,$01,$62,$91,$01,$67,$01,$6a,$8d,$00,$85
	.byte $ff,$0e
	.word @ref134
@ref137:
	.byte $67,$01,$62,$ad,$00,$85
@ref138:
	.byte $3a,$85,$01,$3d,$40,$89,$01,$52,$89,$01,$4a,$89,$00,$81
@ref139:
	.byte $4f,$01,$4a,$95,$00,$9d
@ref140:
	.byte $3c,$85,$01,$3f,$42,$89,$01,$54,$89,$01,$50,$89,$00,$81
@ref141:
	.byte $55,$01,$50,$95,$00,$9d
	.byte $ff,$0e
	.word @ref138
@ref143:
	.byte $4f,$01,$4a,$91,$01,$4f,$01,$52,$8d,$00,$85
	.byte $ff,$0e
	.word @ref138
@ref145:
	.byte $4f,$01,$4a,$ad,$00,$85
	.byte $fd
	.word @song5ch0loop

@song5ch1:
@song5ch1loop:
@ref146:
	.byte $90,$4b,$01,$53,$01,$4b,$01,$53,$01,$4f,$01,$55,$01,$4f,$01,$55
	.byte $00,$81
@ref147:
	.byte $4b,$01,$53,$01,$4b,$01,$53,$01,$4f,$01,$55,$01,$4f,$01,$55,$00
	.byte $81
	.byte $ff,$11
	.word @ref147
	.byte $ff,$11
	.word @ref147
	.byte $ff,$11
	.word @ref147
	.byte $ff,$11
	.word @ref147
	.byte $ff,$11
	.word @ref147
	.byte $ff,$11
	.word @ref147
	.byte $ff,$11
	.word @ref147
	.byte $ff,$11
	.word @ref147
	.byte $ff,$11
	.word @ref147
@ref157:
	.byte $4b,$01,$53,$01,$4b,$01,$53,$01,$4f,$01,$55,$01,$4f,$01,$54,$85
	.byte $ff,$11
	.word @ref147
	.byte $ff,$11
	.word @ref147
	.byte $ff,$11
	.word @ref147
	.byte $ff,$11
	.word @ref147
	.byte $fd
	.word @song5ch1loop

@song5ch2:
@song5ch2loop:
@ref162:
	.byte $9c,$1e,$8d,$18,$8d,$18,$8d,$18,$8d
@ref163:
	.byte $1e,$8d,$14,$8d,$18,$8d,$18,$85,$18,$85
@ref164:
	.byte $1e,$8d,$18,$8d,$18,$8d,$18,$8d
	.byte $ff,$0a
	.word @ref163
	.byte $ff,$08
	.word @ref164
	.byte $ff,$0a
	.word @ref163
	.byte $ff,$08
	.word @ref164
	.byte $ff,$0a
	.word @ref163
	.byte $ff,$08
	.word @ref164
	.byte $ff,$0a
	.word @ref163
	.byte $ff,$08
	.word @ref164
	.byte $ff,$0a
	.word @ref163
	.byte $ff,$08
	.word @ref164
	.byte $ff,$0a
	.word @ref163
	.byte $ff,$08
	.word @ref164
	.byte $ff,$0a
	.word @ref163
	.byte $fd
	.word @song5ch2loop

@song5ch3:
@song5ch3loop:
@ref178:
	.byte $98,$05,$05,$1a,$85,$05,$05,$1a,$85,$05,$05,$1a,$85,$05,$05,$1a
	.byte $85
@ref179:
	.byte $05,$05,$1a,$85,$05,$05,$1b,$05,$05,$05,$1b,$05,$05,$05,$1b,$20
	.byte $81
@ref180:
	.byte $05,$05,$1a,$85,$05,$05,$1a,$85,$05,$05,$1a,$85,$05,$05,$1a,$85
	.byte $ff,$11
	.word @ref179
	.byte $ff,$10
	.word @ref180
	.byte $ff,$11
	.word @ref179
	.byte $ff,$10
	.word @ref180
	.byte $ff,$11
	.word @ref179
	.byte $ff,$10
	.word @ref180
	.byte $ff,$11
	.word @ref179
	.byte $ff,$10
	.word @ref180
	.byte $ff,$11
	.word @ref179
	.byte $ff,$10
	.word @ref180
	.byte $ff,$11
	.word @ref179
	.byte $ff,$10
	.word @ref180
	.byte $ff,$11
	.word @ref179
	.byte $fd
	.word @song5ch3loop

@song5ch4:
@song5ch4loop:
@ref194:
	.byte $bf
@ref195:
	.byte $bf
@ref196:
	.byte $bf
@ref197:
	.byte $bf
@ref198:
	.byte $bf
@ref199:
	.byte $bf
@ref200:
	.byte $bf
@ref201:
	.byte $bf
@ref202:
	.byte $bf
@ref203:
	.byte $bf
@ref204:
	.byte $bf
@ref205:
	.byte $bf
@ref206:
	.byte $bf
@ref207:
	.byte $bf
@ref208:
	.byte $bf
@ref209:
	.byte $bf
	.byte $fd
	.word @song5ch4loop


@song6ch0:
	.byte $fb,$03
@song6ch0loop:
@ref210:
	.byte $96,$38,$8d,$00,$85,$38,$83,$00,$3e,$85,$00,$85,$39,$01,$35,$01
	.byte $38,$8d,$00,$ad
@ref211:
	.byte $92,$59,$5d,$67,$59,$5d,$67,$59,$5d,$67,$59,$5d,$67,$41,$45,$4f
	.byte $41,$45,$4f,$41,$45,$4f,$41,$45,$4f,$00,$8d,$90,$54,$8d
	.byte $fd
	.word @song6ch0loop

@song6ch1:
@song6ch1loop:
@ref212:
	.byte $f9,$85
@ref213:
	.byte $92,$41,$45,$4f,$41,$45,$4f,$41,$45,$4f,$41,$45,$4f,$29,$2d,$37
	.byte $29,$2d,$37,$29,$2d,$37,$29,$2d,$36,$a1
	.byte $fd
	.word @song6ch1loop

@song6ch2:
@song6ch2loop:
@ref214:
	.byte $f9,$85
@ref215:
	.byte $f9,$85
	.byte $fd
	.word @song6ch2loop

@song6ch3:
@song6ch3loop:
@ref216:
	.byte $f9,$85
@ref217:
	.byte $9c,$09,$09,$0d,$09,$09,$0d,$09,$09,$0d,$09,$09,$0d,$09,$09,$0d
	.byte $09,$09,$0d,$09,$09,$0d,$09,$0d,$0c,$a1
	.byte $fd
	.word @song6ch3loop

@song6ch4:
@song6ch4loop:
@ref218:
	.byte $f9,$85
@ref219:
	.byte $f9,$85
	.byte $fd
	.word @song6ch4loop


@song7ch0:
	.byte $fb,$03
@song7ch0loop:
@ref220:
	.byte $a5,$8a,$32,$3a,$32,$3a,$40,$3c,$36,$3e,$36,$3e,$48,$48,$3c
@ref221:
	.byte $3a,$32,$bb
@ref222:
	.byte $92,$58,$bd
@ref223:
	.byte $bf
	.byte $ff,$0e
	.word @ref130
@ref225:
	.byte $67,$01,$62,$95,$00,$9d
	.byte $fd
	.word @song7ch0loop

@song7ch1:
@song7ch1loop:
@ref226:
	.byte $bf
@ref227:
	.byte $bf
@ref228:
	.byte $92,$41,$45,$4f,$41,$45,$4f,$41,$45,$4f,$41,$45,$4f,$29,$2d,$37
	.byte $28,$81
@ref229:
	.byte $2d,$37,$29,$2d,$37,$29,$2d,$36,$a1
	.byte $ff,$11
	.word @ref146
	.byte $ff,$11
	.word @ref147
	.byte $fd
	.word @song7ch1loop

@song7ch2:
@song7ch2loop:
	.byte $ff,$08
	.word @ref162
	.byte $ff,$0a
	.word @ref163
@ref234:
	.byte $bf
@ref235:
	.byte $bf
	.byte $ff,$08
	.word @ref164
	.byte $ff,$0a
	.word @ref163
	.byte $fd
	.word @song7ch2loop

@song7ch3:
@song7ch3loop:
	.byte $ff,$10
	.word @ref178
	.byte $ff,$11
	.word @ref179
@ref240:
	.byte $9c,$09,$09,$0d,$09,$09,$0d,$09,$09,$0d,$09,$09,$0d,$09,$09,$0d
	.byte $08,$81
@ref241:
	.byte $09,$0d,$09,$09,$0d,$09,$0d,$0c,$a1
	.byte $ff,$10
	.word @ref178
	.byte $ff,$11
	.word @ref179
	.byte $fd
	.word @song7ch3loop

@song7ch4:
@song7ch4loop:
@ref244:
	.byte $bf
@ref245:
	.byte $bf
@ref246:
	.byte $bf
@ref247:
	.byte $bf
@ref248:
	.byte $bf
@ref249:
	.byte $bf
	.byte $fd
	.word @song7ch4loop


@song8ch0:
	.byte $fb,$05
@song8ch0loop:
	.byte $ff,$0e
	.word @ref130
	.byte $ff,$06
	.word @ref131
	.byte $ff,$0e
	.word @ref132
	.byte $ff,$06
	.word @ref133
	.byte $ff,$0e
	.word @ref134
	.byte $ff,$0b
	.word @ref135
	.byte $ff,$0e
	.word @ref134
	.byte $ff,$06
	.word @ref137
	.byte $ff,$0e
	.word @ref138
	.byte $ff,$06
	.word @ref139
	.byte $ff,$0e
	.word @ref140
	.byte $ff,$06
	.word @ref141
	.byte $ff,$0e
	.word @ref138
	.byte $ff,$0b
	.word @ref143
	.byte $ff,$0e
	.word @ref138
	.byte $ff,$06
	.word @ref145
	.byte $fd
	.word @song8ch0loop

@song8ch1:
@song8ch1loop:
	.byte $ff,$11
	.word @ref146
	.byte $ff,$11
	.word @ref147
	.byte $ff,$11
	.word @ref147
	.byte $ff,$11
	.word @ref147
	.byte $ff,$11
	.word @ref147
	.byte $ff,$11
	.word @ref147
	.byte $ff,$11
	.word @ref147
	.byte $ff,$11
	.word @ref147
	.byte $ff,$11
	.word @ref147
	.byte $ff,$11
	.word @ref147
	.byte $ff,$11
	.word @ref147
	.byte $ff,$10
	.word @ref157
	.byte $ff,$11
	.word @ref147
	.byte $ff,$11
	.word @ref147
	.byte $ff,$11
	.word @ref147
	.byte $ff,$11
	.word @ref147
	.byte $fd
	.word @song8ch1loop

@song8ch2:
@song8ch2loop:
	.byte $ff,$08
	.word @ref162
	.byte $ff,$0a
	.word @ref163
	.byte $ff,$08
	.word @ref164
	.byte $ff,$0a
	.word @ref163
	.byte $ff,$08
	.word @ref164
	.byte $ff,$0a
	.word @ref163
	.byte $ff,$08
	.word @ref164
	.byte $ff,$0a
	.word @ref163
	.byte $ff,$08
	.word @ref164
	.byte $ff,$0a
	.word @ref163
	.byte $ff,$08
	.word @ref164
	.byte $ff,$0a
	.word @ref163
	.byte $ff,$08
	.word @ref164
	.byte $ff,$0a
	.word @ref163
	.byte $ff,$08
	.word @ref164
	.byte $ff,$0a
	.word @ref163
	.byte $fd
	.word @song8ch2loop

@song8ch3:
@song8ch3loop:
	.byte $ff,$10
	.word @ref178
	.byte $ff,$11
	.word @ref179
	.byte $ff,$10
	.word @ref180
	.byte $ff,$11
	.word @ref179
	.byte $ff,$10
	.word @ref180
	.byte $ff,$11
	.word @ref179
	.byte $ff,$10
	.word @ref180
	.byte $ff,$11
	.word @ref179
	.byte $ff,$10
	.word @ref180
	.byte $ff,$11
	.word @ref179
	.byte $ff,$10
	.word @ref180
	.byte $ff,$11
	.word @ref179
	.byte $ff,$10
	.word @ref180
	.byte $ff,$11
	.word @ref179
	.byte $ff,$10
	.word @ref180
	.byte $ff,$11
	.word @ref179
	.byte $fd
	.word @song8ch3loop

@song8ch4:
@song8ch4loop:
@ref314:
	.byte $bf
@ref315:
	.byte $bf
@ref316:
	.byte $bf
@ref317:
	.byte $bf
@ref318:
	.byte $bf
@ref319:
	.byte $bf
@ref320:
	.byte $bf
@ref321:
	.byte $bf
@ref322:
	.byte $bf
@ref323:
	.byte $bf
@ref324:
	.byte $bf
@ref325:
	.byte $bf
@ref326:
	.byte $bf
@ref327:
	.byte $bf
@ref328:
	.byte $bf
@ref329:
	.byte $bf
	.byte $fd
	.word @song8ch4loop


@song9ch0:
	.byte $fb,$08
@song9ch0loop:
@ref330:
	.byte $86,$1a,$1a,$22,$28,$41,$3b,$1e,$1e,$26,$2c,$45,$3f,$22,$22,$2a
	.byte $30,$49,$43,$40,$3c,$3a,$36,$33,$00,$c1
	.byte $fd
	.word @song9ch0loop

@song9ch1:
@song9ch1loop:
@ref331:
	.byte $90,$02,$02,$0a,$10,$29,$23,$06,$06,$0e,$14,$2d,$27,$0a,$0a,$12
	.byte $18,$31,$2b,$28,$24,$22,$1e,$1b,$00,$c1
	.byte $fd
	.word @song9ch1loop

@song9ch2:
@song9ch2loop:
@ref332:
	.byte $f9,$85
	.byte $fd
	.word @song9ch2loop

@song9ch3:
@song9ch3loop:
@ref333:
	.byte $a4,$08,$08,$09,$10,$85,$08,$08,$09,$10,$85,$08,$08,$09,$10,$85
	.byte $12,$12,$10,$10,$09,$00,$c1
	.byte $fd
	.word @song9ch3loop

@song9ch4:
@song9ch4loop:
@ref334:
	.byte $f9,$85
	.byte $fd
	.word @song9ch4loop


@song10ch0:
	.byte $fb,$03
@song10ch0loop:
@ref335:
	.byte $00,$f9,$83
@ref336:
	.byte $00,$f9,$83
@ref337:
	.byte $00,$f9,$83
@ref338:
	.byte $00,$f9,$83
@ref339:
	.byte $90,$4a,$85,$52,$85,$50,$85,$52,$85,$58,$85,$52,$85,$50,$85,$52
	.byte $85,$4a,$85,$52,$85,$50,$85,$52,$85,$58,$85,$52,$85,$50,$85,$52
	.byte $85
@ref340:
	.byte $4a,$85,$52,$85,$50,$85,$52,$85,$58,$85,$52,$85,$50,$85,$52,$85
	.byte $4a,$85,$52,$85,$50,$85,$52,$85,$58,$85,$52,$85,$50,$85,$52,$85
@ref341:
	.byte $52,$85,$58,$85,$56,$85,$58,$85,$60,$85,$58,$85,$56,$85,$58,$85
	.byte $52,$85,$58,$85,$56,$85,$58,$85,$60,$85,$58,$85,$56,$85,$58,$85
	.byte $ff,$20
	.word @ref341
	.byte $ff,$20
	.word @ref340
	.byte $ff,$20
	.word @ref340
	.byte $ff,$20
	.word @ref341
	.byte $ff,$20
	.word @ref341
	.byte $fd
	.word @song10ch0loop

@song10ch1:
@song10ch1loop:
@ref347:
	.byte $84,$03,$01,$03,$00,$a1,$03,$01,$03,$00,$a1,$06,$8d,$00,$8d
@ref348:
	.byte $03,$01,$03,$00,$a1,$03,$01,$03,$00,$a1,$06,$8d,$00,$8d
@ref349:
	.byte $0b,$01,$0b,$00,$a1,$0b,$01,$0b,$00,$a1,$10,$8d,$00,$8d
	.byte $ff,$0e
	.word @ref349
	.byte $ff,$0e
	.word @ref348
	.byte $ff,$0e
	.word @ref348
	.byte $ff,$0e
	.word @ref349
	.byte $ff,$0e
	.word @ref349
	.byte $ff,$0e
	.word @ref348
	.byte $ff,$0e
	.word @ref348
	.byte $ff,$0e
	.word @ref349
	.byte $ff,$0e
	.word @ref349
	.byte $fd
	.word @song10ch1loop

@song10ch2:
@song10ch2loop:
@ref359:
	.byte $00,$f9,$83
@ref360:
	.byte $00,$f9,$83
@ref361:
	.byte $00,$f9,$83
@ref362:
	.byte $00,$f9,$83
@ref363:
	.byte $98,$4a,$85,$52,$85,$50,$85,$52,$85,$58,$85,$52,$85,$50,$85,$52
	.byte $85,$4a,$85,$52,$85,$50,$85,$52,$85,$58,$85,$52,$85,$50,$85,$52
	.byte $85
	.byte $ff,$20
	.word @ref340
	.byte $ff,$20
	.word @ref341
	.byte $ff,$20
	.word @ref341
	.byte $ff,$20
	.word @ref340
	.byte $ff,$20
	.word @ref340
	.byte $ff,$20
	.word @ref341
	.byte $ff,$20
	.word @ref341
	.byte $fd
	.word @song10ch2loop

@song10ch3:
@song10ch3loop:
@ref371:
	.byte $84,$21,$00,$89,$21,$00,$89,$05,$00,$89,$21,$01,$21,$00,$a1,$05
	.byte $00,$99
@ref372:
	.byte $21,$00,$89,$21,$00,$89,$05,$00,$89,$21,$01,$21,$00,$a1,$05,$00
	.byte $99
@ref373:
	.byte $03,$00,$89,$03,$00,$89,$07,$00,$89,$03,$01,$03,$00,$a1,$07,$00
	.byte $99
	.byte $ff,$11
	.word @ref373
	.byte $ff,$11
	.word @ref372
	.byte $ff,$11
	.word @ref372
	.byte $ff,$11
	.word @ref373
	.byte $ff,$11
	.word @ref373
	.byte $ff,$11
	.word @ref372
	.byte $ff,$11
	.word @ref372
	.byte $ff,$11
	.word @ref373
	.byte $ff,$11
	.word @ref373
	.byte $fd
	.word @song10ch3loop

@song10ch4:
@song10ch4loop:
@ref383:
	.byte $f9,$85
@ref384:
	.byte $f9,$85
@ref385:
	.byte $f9,$85
@ref386:
	.byte $f9,$85
@ref387:
	.byte $f9,$85
@ref388:
	.byte $f9,$85
@ref389:
	.byte $f9,$85
@ref390:
	.byte $f9,$85
@ref391:
	.byte $f9,$85
@ref392:
	.byte $f9,$85
@ref393:
	.byte $f9,$85
@ref394:
	.byte $f9,$85
	.byte $fd
	.word @song10ch4loop


@song11ch0:
	.byte $fb,$08
@song11ch0loop:
@ref395:
	.byte $a8,$4b,$4e,$52,$83,$58,$83,$58,$83,$5d,$58,$91,$4b,$4e,$52,$83
	.byte $58,$83,$5c,$83,$61,$5c,$91,$4b,$4e,$52,$83,$58,$83,$58,$83,$55
	.byte $52,$81
@ref396:
	.byte $83,$4f,$4a,$83,$00,$4b,$4e,$52,$83,$58,$83,$52,$83,$4f,$4a,$93
	.byte $fd
	.word @song11ch0loop

@song11ch1:
@song11ch1loop:
@ref397:
	.byte $81,$a8,$4b,$4e,$52,$83,$58,$83,$58,$83,$5d,$58,$91,$4b,$4e,$52
	.byte $83,$58,$83,$5c,$83,$61,$5c,$91,$4b,$4e,$52,$83,$58,$83,$58,$83
	.byte $55,$52
@ref398:
	.byte $85,$4f,$4a,$83,$00,$4b,$4e,$52,$83,$58,$83,$52,$83,$4f,$4a,$91
	.byte $fd
	.word @song11ch1loop

@song11ch2:
@song11ch2loop:
@ref399:
	.byte $9e,$17,$1a,$1e,$83,$24,$83,$24,$83,$29,$24,$89,$00,$85,$17,$1a
	.byte $1e,$83,$24,$83,$28,$83,$2d,$28,$89,$00,$85,$17,$1a,$1e,$83,$24
	.byte $83,$24,$83,$21,$1e,$81
@ref400:
	.byte $83,$19,$14,$83,$00,$15,$18,$1c,$83,$22,$83,$1c,$83,$19,$14,$89
	.byte $0a,$02,$85
	.byte $fd
	.word @song11ch2loop

@song11ch3:
@song11ch3loop:
@ref401:
	.byte $ac,$20,$83,$04,$83,$20,$20,$20,$20,$83,$04,$04,$08,$08,$87,$08
	.byte $08,$83,$20,$83,$04,$83,$20,$20,$20,$20,$83,$04,$04,$08,$08,$87
	.byte $08,$08,$83,$20,$83,$04,$83,$20,$20,$20,$20,$83,$04,$04,$08,$08
@ref402:
	.byte $83,$04,$04,$08,$08,$83,$20,$83,$04,$83,$20,$20,$20,$20,$83,$04
	.byte $04,$08,$08,$87,$08,$08,$85
	.byte $fd
	.word @song11ch3loop

@song11ch4:
@song11ch4loop:
@ref403:
	.byte $f9,$85
@ref404:
	.byte $c1
	.byte $fd
	.word @song11ch4loop


@song12ch0:
	.byte $fb,$06
@ref405:
	.byte $00,$f9,$83
@song12ch0loop:
@ref406:
	.byte $f9,$85
	.byte $fd
	.word @song12ch0loop

@song12ch1:
@ref407:
	.byte $00,$f9,$83
@song12ch1loop:
@ref408:
	.byte $aa,$02,$83,$02,$b7,$02,$83,$02,$b7
	.byte $fd
	.word @song12ch1loop

@song12ch2:
@ref409:
	.byte $a0,$18,$16,$14,$12,$10,$0e,$0c,$0a,$08,$06,$04,$02,$e7
@song12ch2loop:
@ref410:
	.byte $f9,$85
	.byte $fd
	.word @song12ch2loop

@song12ch3:
@ref411:
	.byte $00,$95,$96,$04,$00,$83,$1c,$9d,$00,$bd
@song12ch3loop:
@ref412:
	.byte $f9,$85
	.byte $fd
	.word @song12ch3loop

@song12ch4:
@ref413:
	.byte $f9,$85
@song12ch4loop:
@ref414:
	.byte $f9,$85
	.byte $fd
	.word @song12ch4loop


@song13ch0:
	.byte $fb,$04
@song13ch0loop:
@ref415:
	.byte $8e,$32,$95,$3a,$85,$40,$95,$44,$85
@ref416:
	.byte $48,$95,$44,$85,$40,$9d
@ref417:
	.byte $00,$bd
@ref418:
	.byte $22,$85,$28,$85,$30,$85,$22,$85,$28,$85,$30,$85,$22,$85,$28,$85
@ref419:
	.byte $30,$85,$22,$85,$28,$85,$30,$85,$1e,$85,$24,$85,$2c,$85,$1e,$85
@ref420:
	.byte $24,$85,$2c,$85,$1e,$85,$24,$85,$2c,$85,$1e,$85,$24,$85,$2c,$85
	.byte $ff,$10
	.word @ref418
@ref422:
	.byte $30,$85,$22,$85,$28,$85,$30,$85,$24,$85,$2c,$85,$32,$85,$24,$85
@ref423:
	.byte $2c,$85,$32,$85,$24,$85,$2c,$85,$32,$85,$24,$85,$2c,$85,$32,$85
@ref424:
	.byte $22,$8d,$00,$ad
	.byte $fd
	.word @song13ch0loop

@song13ch1:
@song13ch1loop:
@ref425:
	.byte $81,$88,$1a,$95,$22,$85,$28,$95,$2c,$83
@ref426:
	.byte $81,$30,$95,$2c,$85,$28,$9b
@ref427:
	.byte $00,$bd
@ref428:
	.byte $8e,$3a,$95,$3a,$95,$3a,$8d
@ref429:
	.byte $87,$3a,$95,$36,$95,$36,$85
@ref430:
	.byte $8f,$36,$95,$36,$95
@ref431:
	.byte $3a,$95,$3a,$95,$3a,$8d
@ref432:
	.byte $87,$3a,$95,$3c,$95,$3c,$85
@ref433:
	.byte $8f,$3c,$95,$3c,$95
@ref434:
	.byte $3a,$8d,$00,$ad
	.byte $fd
	.word @song13ch1loop

@song13ch2:
@song13ch2loop:
@ref435:
	.byte $bf
@ref436:
	.byte $bf
@ref437:
	.byte $bf
@ref438:
	.byte $bf
@ref439:
	.byte $bf
@ref440:
	.byte $bf
@ref441:
	.byte $bf
@ref442:
	.byte $bf
@ref443:
	.byte $bf
@ref444:
	.byte $8f,$00,$ad
	.byte $fd
	.word @song13ch2loop

@song13ch3:
@song13ch3loop:
@ref445:
	.byte $bf
@ref446:
	.byte $bf
@ref447:
	.byte $88,$02,$07,$00,$b7
@ref448:
	.byte $bf
@ref449:
	.byte $bf
@ref450:
	.byte $bf
@ref451:
	.byte $bf
@ref452:
	.byte $bf
@ref453:
	.byte $bf
@ref454:
	.byte $8f,$00,$ad
	.byte $fd
	.word @song13ch3loop

@song13ch4:
@song13ch4loop:
@ref455:
	.byte $bf
@ref456:
	.byte $bf
@ref457:
	.byte $bf
@ref458:
	.byte $bf
@ref459:
	.byte $bf
@ref460:
	.byte $bf
@ref461:
	.byte $bf
@ref462:
	.byte $bf
@ref463:
	.byte $bf
@ref464:
	.byte $bf
	.byte $fd
	.word @song13ch4loop
