;this file for FamiTone2 library generated by text2data tool

music_music_data:
	.byte 15
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,245,204
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,245,204
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,307,256
	.word @song4ch0,@song4ch1,@song4ch2,@song4ch3,@song4ch4,307,256
	.word @song5ch0,@song5ch1,@song5ch2,@song5ch3,@song5ch4,307,256
	.word @song6ch0,@song6ch1,@song6ch2,@song6ch3,@song6ch4,307,256
	.word @song7ch0,@song7ch1,@song7ch2,@song7ch3,@song7ch4,307,256
	.word @song8ch0,@song8ch1,@song8ch2,@song8ch3,@song8ch4,307,256
	.word @song9ch0,@song9ch1,@song9ch2,@song9ch3,@song9ch4,307,256
	.word @song10ch0,@song10ch1,@song10ch2,@song10ch3,@song10ch4,409,341
	.word @song11ch0,@song11ch1,@song11ch2,@song11ch3,@song11ch4,307,256
	.word @song12ch0,@song12ch1,@song12ch2,@song12ch3,@song12ch4,307,256
	.word @song13ch0,@song13ch1,@song13ch2,@song13ch3,@song13ch4,307,256
	.word @song14ch0,@song14ch1,@song14ch2,@song14ch3,@song14ch4,307,256

@instruments:
	.byte $30 ;instrument $01
	.word @env2,@env0,@env31
	.byte $00
	.byte $b0 ;instrument $05
	.word @env3,@env0,@env32
	.byte $00
	.byte $b0 ;instrument $0d
	.word @env4,@env0,@env0
	.byte $00
	.byte $30 ;instrument $0e
	.word @env5,@env0,@env33
	.byte $00
	.byte $30 ;instrument $0f
	.word @env6,@env0,@env0
	.byte $00
	.byte $30 ;instrument $10
	.word @env4,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $12
	.word @env4,@env0,@env0
	.byte $00
	.byte $70 ;instrument $13
	.word @env5,@env0,@env33
	.byte $00
	.byte $b0 ;instrument $14
	.word @env6,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $15
	.word @env4,@env0,@env0
	.byte $00
	.byte $30 ;instrument $17
	.word @env1,@env0,@env0
	.byte $00
	.byte $30 ;instrument $1e
	.word @env7,@env0,@env0
	.byte $00
	.byte $30 ;instrument $1f
	.word @env8,@env0,@env0
	.byte $00
	.byte $30 ;instrument $22
	.word @env9,@env23,@env0
	.byte $00
	.byte $30 ;instrument $23
	.word @env10,@env0,@env0
	.byte $00
	.byte $30 ;instrument $26
	.word @env11,@env24,@env0
	.byte $00
	.byte $30 ;instrument $27
	.word @env12,@env25,@env0
	.byte $00
	.byte $30 ;instrument $28
	.word @env13,@env26,@env0
	.byte $00
	.byte $30 ;instrument $2a
	.word @env14,@env0,@env0
	.byte $00
	.byte $30 ;instrument $2d
	.word @env15,@env27,@env0
	.byte $00
	.byte $b0 ;instrument $2f
	.word @env16,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $30
	.word @env17,@env28,@env0
	.byte $00
	.byte $b0 ;instrument $31
	.word @env18,@env29,@env32
	.byte $00
	.byte $30 ;instrument $32
	.word @env19,@env27,@env0
	.byte $00
	.byte $f0 ;instrument $33
	.word @env20,@env30,@env0
	.byte $00
	.byte $30 ;instrument $34
	.word @env21,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $35
	.word @env22,@env0,@env34
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$00,$00
@env2:
	.byte $c3,$00,$00
@env3:
	.byte $cb,$ce,$c9,$c4,$c1,$c0,$00,$05
@env4:
	.byte $c8,$c7,$c6,$c6,$c5,$c5,$c4,$00,$06
@env5:
	.byte $c2,$c4,$c6,$c6,$c7,$c7,$c8,$c7,$c6,$c5,$c5,$c4,$00,$0b
@env6:
	.byte $c2,$c8,$c6,$c5,$c5,$c4,$c4,$00,$06
@env7:
	.byte $cf,$09,$c0,$cf,$c0,$c0,$cf,$c0,$c0,$cf,$c0,$c0,$cf,$c0,$c0,$cf
	.byte $c0,$02,$cf,$c0,$02,$cf,$c0,$00,$16
@env8:
	.byte $c8,$c0,$00,$01
@env9:
	.byte $ca,$c3,$c2,$c1,$c0,$00,$04
@env10:
	.byte $c8,$c7,$c6,$c5,$02,$c4,$02,$c0,$00,$07
@env11:
	.byte $ca,$c8,$c7,$c6,$c6,$c5,$02,$c4,$c4,$c3,$c2,$c0,$00,$0b
@env12:
	.byte $cd,$cb,$c9,$c7,$c6,$c5,$c5,$c4,$c4,$c3,$c3,$c2,$04,$c1,$03,$c0
	.byte $00,$0f
@env13:
	.byte $cf,$c8,$c6,$c5,$c4,$c3,$c2,$c2,$c1,$c1,$c0,$00,$0a
@env14:
	.byte $c2,$00,$00
@env15:
	.byte $c8,$c3,$c2,$c2,$c1,$02,$c0,$00,$06
@env16:
	.byte $c4,$c4,$c3,$03,$c2,$00,$04
@env17:
	.byte $c2,$c8,$c6,$c5,$c5,$c4,$11,$c3,$02,$c2,$02,$c1,$03,$c0,$00,$0d
@env18:
	.byte $c7,$c9,$c6,$c2,$c1,$c0,$00,$05
@env19:
	.byte $c4,$c2,$c2,$c1,$c1,$c0,$00,$05
@env20:
	.byte $ca,$c8,$c5,$c3,$c2,$c3,$c4,$c5,$c6,$c7,$c9,$00,$00
@env21:
	.byte $cb,$00,$00
@env22:
	.byte $c0,$c1,$c2,$c3,$c4,$c4,$c5,$c4,$c4,$c3,$c3,$c2,$c1,$00,$0c
@env23:
	.byte $c0,$c2,$c0,$00,$02
@env24:
	.byte $c0,$c2,$c1,$c1,$c2,$c2,$00,$05
@env25:
	.byte $c0,$c0,$c1,$c1,$c2,$c2,$c3,$00,$06
@env26:
	.byte $c0,$c1,$c2,$c3,$00,$03
@env27:
	.byte $c0,$c8,$cb,$cd,$ce,$00,$04
@env28:
	.byte $c5,$00,$00
@env29:
	.byte $c0,$c1,$00,$01
@env30:
	.byte $c0,$c0,$c1,$c2,$c2,$c1,$c0,$c0,$00,$07
@env31:
	.byte $ca,$da,$00,$01
@env32:
	.byte $ff,$00,$00
@env33:
	.byte $c0,$1f,$c1,$c2,$02,$c1,$c0,$00,$02
@env34:
	.byte $ba,$b4,$02,$b4,$00,$03


@song0ch0:
	.byte $fb,$06
@ref0:
	.byte $8e,$0a,$85,$01,$0d,$10,$89,$01,$22,$89,$01,$1a,$89,$01,$1f,$01
	.byte $1a,$a5,$00,$8d
@ref1:
	.byte $0c,$85,$01,$0f,$12,$89,$01,$24,$89,$01,$20,$89,$01,$25,$01,$20
	.byte $a5,$00,$8d
@ref2:
	.byte $0a,$85,$01,$0d,$10,$89,$01,$22,$89,$01,$1a,$89,$01,$1f,$01,$1a
	.byte $91,$01,$1f,$01,$22,$8d,$00,$85
@ref3:
	.byte $0a,$85,$01,$0d,$10,$89,$01,$22,$89,$01,$1a,$89,$01,$1f,$01,$1a
	.byte $ad,$00,$85
@ref4:
	.byte $0a,$85,$01,$0d,$10,$89,$01,$22,$89,$01,$1a,$89,$01,$1f,$01,$1a
	.byte $a5,$00,$8d
	.byte $ff,$13
	.word @ref1
	.byte $ff,$18
	.word @ref2
	.byte $ff,$13
	.word @ref3
	.byte $ff,$13
	.word @ref4
	.byte $ff,$13
	.word @ref1
	.byte $ff,$18
	.word @ref2
	.byte $ff,$13
	.word @ref3
@song0ch0loop:
@ref12:
	.byte $a0,$52,$85,$01,$55,$58,$89,$01,$6a,$89,$01,$62,$89,$01,$67,$01
	.byte $62,$a5,$00,$8d
@ref13:
	.byte $54,$85,$01,$57,$5a,$89,$01,$6c,$89,$01,$68,$89,$01,$6d,$01,$68
	.byte $a5,$00,$8d
@ref14:
	.byte $52,$85,$01,$55,$58,$89,$01,$6a,$89,$01,$62,$89,$01,$67,$01,$62
	.byte $91,$01,$67,$01,$6a,$8d,$00,$85
@ref15:
	.byte $52,$85,$01,$55,$58,$89,$01,$6a,$89,$01,$62,$89,$01,$67,$01,$62
	.byte $ad,$00,$85
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@ref16:
	.byte $8e,$32,$85,$01,$37,$3a,$89,$01,$4a,$89,$01,$44,$89,$01,$49,$01
	.byte $44,$a5,$00,$8d
@ref17:
	.byte $36,$85,$01,$39,$3c,$89,$01,$4e,$89,$01,$4a,$89,$01,$4f,$01,$4a
	.byte $a5,$00,$8d
@ref18:
	.byte $34,$85,$01,$37,$3a,$89,$01,$4c,$89,$01,$44,$89,$01,$49,$01,$44
	.byte $91,$01,$49,$01,$4c,$8d,$00,$85
@ref19:
	.byte $32,$85,$01,$37,$3a,$89,$01,$4a,$89,$01,$44,$89,$01,$49,$01,$44
	.byte $ad,$00,$85
@ref20:
	.byte $32,$85,$01,$37,$3a,$89,$01,$4a,$89,$01,$44,$89,$01,$49,$01,$44
	.byte $a5,$00,$8d
	.byte $ff,$13
	.word @ref17
	.byte $ff,$18
	.word @ref18
	.byte $ff,$13
	.word @ref19
	.byte $ff,$13
	.word @ref20
	.byte $ff,$13
	.word @ref17
	.byte $ff,$18
	.word @ref18
	.byte $ff,$13
	.word @ref19
@song0ch1loop:
@ref28:
	.byte $f9,$85
@ref29:
	.byte $f9,$85
@ref30:
	.byte $f9,$85
@ref31:
	.byte $f9,$85
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@ref32:
	.byte $f9,$85
@ref33:
	.byte $f9,$85
@ref34:
	.byte $f9,$85
@ref35:
	.byte $f9,$85
@ref36:
	.byte $f9,$85
@ref37:
	.byte $f9,$85
@ref38:
	.byte $f9,$85
@ref39:
	.byte $f9,$85
@ref40:
	.byte $f9,$85
@ref41:
	.byte $f9,$85
@ref42:
	.byte $f9,$85
@ref43:
	.byte $f9,$85
@song0ch2loop:
@ref44:
	.byte $f9,$85
@ref45:
	.byte $f9,$85
@ref46:
	.byte $f9,$85
@ref47:
	.byte $f9,$85
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@ref48:
	.byte $f9,$85
@ref49:
	.byte $f9,$85
@ref50:
	.byte $f9,$85
@ref51:
	.byte $f9,$85
@ref52:
	.byte $f9,$85
@ref53:
	.byte $f9,$85
@ref54:
	.byte $f9,$85
@ref55:
	.byte $f9,$85
@ref56:
	.byte $f9,$85
@ref57:
	.byte $f9,$85
@ref58:
	.byte $f9,$85
@ref59:
	.byte $f9,$85
@song0ch3loop:
@ref60:
	.byte $f9,$85
@ref61:
	.byte $f9,$85
@ref62:
	.byte $f9,$85
@ref63:
	.byte $f9,$85
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@ref64:
	.byte $f9,$85
@ref65:
	.byte $f9,$85
@ref66:
	.byte $f9,$85
@ref67:
	.byte $f9,$85
@ref68:
	.byte $f9,$85
@ref69:
	.byte $f9,$85
@ref70:
	.byte $f9,$85
@ref71:
	.byte $f9,$85
@ref72:
	.byte $f9,$85
@ref73:
	.byte $f9,$85
@ref74:
	.byte $f9,$85
@ref75:
	.byte $f9,$85
@song0ch4loop:
@ref76:
	.byte $f9,$85
@ref77:
	.byte $f9,$85
@ref78:
	.byte $f9,$85
@ref79:
	.byte $f9,$85
	.byte $fd
	.word @song0ch4loop


@song1ch0:
	.byte $fb,$08
@song1ch0loop:
@ref80:
	.byte $84,$62,$63,$6c,$6d,$62,$63,$6c,$6c,$89
@ref81:
	.byte $62,$63,$6c,$6d,$62,$63,$6c,$6c,$89
	.byte $ff,$09
	.word @ref81
	.byte $ff,$09
	.word @ref81
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@song1ch1loop:
@ref84:
	.byte $a4,$02,$85,$02,$87,$06,$8b
@ref85:
	.byte $02,$8d,$0a,$8d
@ref86:
	.byte $02,$85,$02,$87,$06,$8b
@ref87:
	.byte $02,$8d,$0a,$8d
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@song1ch2loop:
@ref88:
	.byte $84,$6c,$70,$75,$7a,$83,$6d,$75,$7a,$85,$00
@ref89:
	.byte $6c,$70,$75,$7a,$83,$6d,$75,$6c,$85,$00
@ref90:
	.byte $6c,$70,$75,$7a,$83,$6d,$75,$7a,$85,$00
	.byte $ff,$0a
	.word @ref89
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@song1ch3loop:
@ref92:
	.byte $98,$1e,$8f,$21,$20,$87
@ref93:
	.byte $1e,$8f,$21,$20,$87
	.byte $ff,$05
	.word @ref93
	.byte $ff,$05
	.word @ref93
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@song1ch4loop:
@ref96:
	.byte $9f
@ref97:
	.byte $9f
@ref98:
	.byte $9f
@ref99:
	.byte $9f
	.byte $fd
	.word @song1ch4loop


@song2ch0:
	.byte $fb,$02
@song2ch0loop:
@ref100:
	.byte $b2,$24,$83,$00,$24,$83,$00,$2c,$8b,$00,$32,$8b,$00,$36,$8b,$00
@ref101:
	.byte $3a,$83,$00,$36,$8b,$00,$3a,$83,$00,$36,$8b,$00,$32,$8b,$00
@ref102:
	.byte $24,$83,$00,$24,$83,$00,$2c,$8b,$00,$32,$8b,$00,$36,$8b,$00
@ref103:
	.byte $3a,$83,$00,$36,$8b,$00,$3a,$83,$00,$32,$9b,$00
	.byte $ff,$0f
	.word @ref102
	.byte $ff,$0f
	.word @ref101
	.byte $ff,$0f
	.word @ref102
@ref107:
	.byte $32,$83,$00,$2c,$8b,$00,$28,$83,$00,$24,$9b,$00
@ref108:
	.byte $81
	.byte $fd
	.word @song2ch0loop

@song2ch1:
@song2ch1loop:
@ref109:
	.byte $b0,$54,$83,$00,$54,$83,$00,$5c,$8b,$00,$62,$8b,$00,$66,$8b,$00
@ref110:
	.byte $6a,$83,$00,$66,$8b,$00,$6a,$83,$00,$66,$8b,$00,$62,$8b,$00
@ref111:
	.byte $54,$83,$00,$54,$83,$00,$5c,$8b,$00,$62,$8b,$00,$66,$8b,$00
@ref112:
	.byte $6a,$83,$00,$66,$8b,$00,$6a,$83,$00,$62,$9b,$00
	.byte $ff,$0f
	.word @ref111
	.byte $ff,$0f
	.word @ref110
	.byte $ff,$0f
	.word @ref111
@ref116:
	.byte $62,$83,$00,$5c,$8b,$00,$58,$83,$00,$54,$9b,$00
@ref117:
	.byte $81
	.byte $fd
	.word @song2ch1loop

@song2ch2:
@song2ch2loop:
@ref118:
	.byte $94,$0c,$83,$00,$0c,$83,$00,$14,$8b,$00,$1a,$8b,$00,$1e,$8b,$00
@ref119:
	.byte $22,$83,$00,$1e,$8b,$00,$22,$83,$00,$1e,$8b,$00,$1a,$8b,$00
@ref120:
	.byte $0c,$83,$00,$0c,$83,$00,$14,$8b,$00,$1a,$8b,$00,$1e,$8b,$00
@ref121:
	.byte $22,$83,$00,$1e,$8b,$00,$22,$83,$00,$1a,$9b,$00
	.byte $ff,$0f
	.word @ref120
	.byte $ff,$0f
	.word @ref119
	.byte $ff,$0f
	.word @ref120
@ref125:
	.byte $1a,$83,$00,$14,$8b,$00,$10,$83,$00,$0c,$9b,$00
@ref126:
	.byte $81
	.byte $fd
	.word @song2ch2loop

@song2ch3:
@song2ch3loop:
@ref127:
	.byte $ae,$08,$85,$08,$85,$08,$8d,$10,$8d,$08,$8d
@ref128:
	.byte $08,$85,$08,$8d,$08,$85,$08,$8d,$10,$8d
@ref129:
	.byte $08,$85,$08,$85,$08,$8d,$10,$8d,$08,$8d
	.byte $ff,$0a
	.word @ref128
	.byte $ff,$0a
	.word @ref129
	.byte $ff,$0a
	.word @ref128
	.byte $ff,$0a
	.word @ref129
	.byte $ff,$0a
	.word @ref128
@ref135:
	.byte $08
	.byte $fd
	.word @song2ch3loop

@song2ch4:
@song2ch4loop:
@ref136:
	.byte $bf
@ref137:
	.byte $bf
@ref138:
	.byte $bf
@ref139:
	.byte $bf
@ref140:
	.byte $bf
@ref141:
	.byte $bf
@ref142:
	.byte $bf
@ref143:
	.byte $bf
@ref144:
	.byte $81
	.byte $fd
	.word @song2ch4loop


@song3ch0:
	.byte $fb,$06
@song3ch0loop:
@ref145:
	.byte $8f,$90,$6c,$74,$83,$6a,$70,$83,$6c,$87,$00,$d3
	.byte $fd
	.word @song3ch0loop

@song3ch1:
@song3ch1loop:
@ref146:
	.byte $8f,$86,$24,$2c,$83,$22,$28,$83,$24,$87,$00,$d3
	.byte $fd
	.word @song3ch1loop

@song3ch2:
@song3ch2loop:
@ref147:
	.byte $a5,$94,$03,$00,$d3
	.byte $fd
	.word @song3ch2loop

@song3ch3:
@song3ch3loop:
@ref148:
	.byte $82,$14,$a7,$00,$d3
	.byte $fd
	.word @song3ch3loop

@song3ch4:
@song3ch4loop:
@ref149:
	.byte $f9,$85
	.byte $fd
	.word @song3ch4loop


@song4ch0:
	.byte $fb,$08
@ref150:
	.byte $00,$bd
@ref151:
	.byte $bf
@song4ch0loop:
@ref152:
	.byte $92,$42,$85,$50,$85,$57,$51,$57,$50,$99,$00,$85
@ref153:
	.byte $5a,$85,$68,$85,$6f,$69,$6f,$68,$99,$00,$85
@ref154:
	.byte $42,$85,$50,$85,$57,$51,$57,$50,$99,$00,$85
	.byte $ff,$0b
	.word @ref153
@ref156:
	.byte $35,$01,$35,$01,$39,$00,$87,$00,$35,$01,$35,$01,$39,$00,$89
@ref157:
	.byte $4d,$01,$4d,$01,$51,$00,$87,$00,$4d,$01,$4d,$01,$51,$00,$89
	.byte $fd
	.word @song4ch0loop

@song4ch1:
@ref158:
	.byte $a8,$02,$83,$00,$10,$83,$00,$02,$02,$02,$10,$83,$01,$02,$83,$00
	.byte $10,$83,$00,$02,$02,$02,$11,$00,$16,$18
@ref159:
	.byte $0a,$83,$00,$18,$83,$00,$0a,$0a,$0a,$19,$20,$21,$0a,$83,$00,$18
	.byte $83,$00,$0a,$0a,$0a,$18,$00,$0c,$0a,$81
@song4ch1loop:
	.byte $ff,$19
	.word @ref158
	.byte $ff,$1a
	.word @ref159
@ref162:
	.byte $02,$83,$00,$10,$83,$00,$02,$02,$02,$10,$83,$01,$02,$83,$00,$10
	.byte $83,$00,$02,$02,$02,$11,$00,$16,$18
	.byte $ff,$1a
	.word @ref159
	.byte $ff,$19
	.word @ref162
	.byte $ff,$1a
	.word @ref159
	.byte $fd
	.word @song4ch1loop

@song4ch2:
@ref166:
	.byte $bf
@ref167:
	.byte $bf
@song4ch2loop:
@ref168:
	.byte $bf
@ref169:
	.byte $bf
@ref170:
	.byte $bf
@ref171:
	.byte $bf
@ref172:
	.byte $bf
@ref173:
	.byte $bf
	.byte $fd
	.word @song4ch2loop

@song4ch3:
@ref174:
	.byte $80,$18,$00,$19,$1c,$00,$1d,$0e,$00,$19,$00,$85,$18,$00,$19,$1c
	.byte $00,$1d,$0e,$00,$19,$00,$85
@ref175:
	.byte $18,$00,$19,$1c,$00,$1d,$0e,$00,$19,$00,$85,$18,$00,$19,$1c,$00
	.byte $1d,$0e,$00,$19,$00,$85
@song4ch3loop:
	.byte $ff,$16
	.word @ref174
	.byte $ff,$16
	.word @ref175
	.byte $ff,$16
	.word @ref175
	.byte $ff,$16
	.word @ref175
	.byte $ff,$16
	.word @ref175
	.byte $ff,$16
	.word @ref175
	.byte $fd
	.word @song4ch3loop

@song4ch4:
@ref182:
	.byte $bf
@ref183:
	.byte $bf
@song4ch4loop:
@ref184:
	.byte $bf
@ref185:
	.byte $bf
@ref186:
	.byte $bf
@ref187:
	.byte $bf
@ref188:
	.byte $bf
@ref189:
	.byte $bf
	.byte $fd
	.word @song4ch4loop


@song5ch0:
	.byte $fb,$03
@song5ch0loop:
@ref190:
	.byte $90,$52,$85,$01,$55,$58,$89,$01,$6a,$89,$01,$62,$89,$01,$67,$01
	.byte $62,$a5,$00,$8d
	.byte $ff,$13
	.word @ref13
	.byte $ff,$18
	.word @ref14
	.byte $ff,$13
	.word @ref15
@ref194:
	.byte $3a,$85,$01,$3d,$40,$89,$01,$52,$89,$01,$4a,$89,$01,$4f,$01,$4a
	.byte $95,$00,$9d
@ref195:
	.byte $3c,$85,$01,$3f,$42,$89,$01,$54,$89,$01,$50,$89,$01,$55,$01,$50
	.byte $95,$00,$9d
@ref196:
	.byte $3a,$85,$01,$3d,$40,$89,$01,$52,$89,$01,$4a,$89,$01,$4f,$01,$4a
	.byte $91,$01,$4f,$01,$52,$8d,$00,$85
@ref197:
	.byte $3a,$85,$01,$3d,$40,$89,$01,$52,$89,$01,$4a,$89,$01,$4f,$01,$4a
	.byte $ad,$00,$85
	.byte $fd
	.word @song5ch0loop

@song5ch1:
@song5ch1loop:
@ref198:
	.byte $90,$4b,$01,$53,$01,$4b,$01,$53,$01,$4f,$01,$55,$01,$4f,$01,$55
	.byte $01,$4b,$01,$53,$01,$4b,$01,$53,$01,$4f,$01,$55,$01,$4f,$01,$55
	.byte $00,$81
@ref199:
	.byte $4b,$01,$53,$01,$4b,$01,$53,$01,$4f,$01,$55,$01,$4f,$01,$55,$01
	.byte $4b,$01,$53,$01,$4b,$01,$53,$01,$4f,$01,$55,$01,$4f,$01,$55,$00
	.byte $81
	.byte $ff,$21
	.word @ref199
	.byte $ff,$21
	.word @ref199
	.byte $ff,$21
	.word @ref199
@ref203:
	.byte $4b,$01,$53,$01,$4b,$01,$53,$01,$4f,$01,$55,$01,$4f,$01,$55,$01
	.byte $4b,$01,$53,$01,$4b,$01,$53,$01,$4f,$01,$55,$01,$4f,$01,$54,$85
	.byte $ff,$21
	.word @ref199
	.byte $ff,$21
	.word @ref199
	.byte $fd
	.word @song5ch1loop

@song5ch2:
@song5ch2loop:
@ref206:
	.byte $9c,$1e,$8d,$18,$8d,$18,$8d,$18,$8d,$1e,$8d,$14,$8d,$18,$8d,$18
	.byte $85,$18,$85
@ref207:
	.byte $1e,$8d,$18,$8d,$18,$8d,$18,$8d,$1e,$8d,$14,$8d,$18,$8d,$18,$85
	.byte $18,$85
	.byte $ff,$12
	.word @ref207
	.byte $ff,$12
	.word @ref207
	.byte $ff,$12
	.word @ref207
	.byte $ff,$12
	.word @ref207
	.byte $ff,$12
	.word @ref207
	.byte $ff,$12
	.word @ref207
	.byte $fd
	.word @song5ch2loop

@song5ch3:
@song5ch3loop:
@ref214:
	.byte $98,$05,$05,$1a,$85,$05,$05,$1a,$85,$05,$05,$1a,$85,$05,$05,$1a
	.byte $85,$05,$05,$1a,$85,$05,$05,$1b,$05,$05,$05,$1b,$05,$05,$05,$1b
	.byte $20,$81
@ref215:
	.byte $05,$05,$1a,$85,$05,$05,$1a,$85,$05,$05,$1a,$85,$05,$05,$1a,$85
	.byte $05,$05,$1a,$85,$05,$05,$1b,$05,$05,$05,$1b,$05,$05,$05,$1b,$20
	.byte $81
	.byte $ff,$21
	.word @ref215
	.byte $ff,$21
	.word @ref215
	.byte $ff,$21
	.word @ref215
	.byte $ff,$21
	.word @ref215
	.byte $ff,$21
	.word @ref215
	.byte $ff,$21
	.word @ref215
	.byte $fd
	.word @song5ch3loop

@song5ch4:
@song5ch4loop:
@ref222:
	.byte $f9,$85
@ref223:
	.byte $f9,$85
@ref224:
	.byte $f9,$85
@ref225:
	.byte $f9,$85
@ref226:
	.byte $f9,$85
@ref227:
	.byte $f9,$85
@ref228:
	.byte $f9,$85
@ref229:
	.byte $f9,$85
	.byte $fd
	.word @song5ch4loop


@song6ch0:
	.byte $fb,$03
@song6ch0loop:
@ref230:
	.byte $96,$38,$8d,$00,$85,$38,$83,$00,$3e,$85,$00,$85,$39,$01,$35,$01
	.byte $38,$8d,$00,$ad
@ref231:
	.byte $92,$59,$5d,$67,$59,$5d,$67,$59,$5d,$67,$59,$5d,$67,$41,$45,$4f
	.byte $41,$45,$4f,$41,$45,$4f,$41,$45,$4f,$00,$8d,$90,$54,$8d
	.byte $fd
	.word @song6ch0loop

@song6ch1:
@song6ch1loop:
@ref232:
	.byte $f9,$85
@ref233:
	.byte $92,$41,$45,$4f,$41,$45,$4f,$41,$45,$4f,$41,$45,$4f,$29,$2d,$37
	.byte $29,$2d,$37,$29,$2d,$37,$29,$2d,$36,$a1
	.byte $fd
	.word @song6ch1loop

@song6ch2:
@song6ch2loop:
@ref234:
	.byte $f9,$85
@ref235:
	.byte $f9,$85
	.byte $fd
	.word @song6ch2loop

@song6ch3:
@song6ch3loop:
@ref236:
	.byte $f9,$85
@ref237:
	.byte $9c,$09,$09,$0d,$09,$09,$0d,$09,$09,$0d,$09,$09,$0d,$09,$09,$0d
	.byte $09,$09,$0d,$09,$09,$0d,$09,$0d,$0c,$a1
	.byte $fd
	.word @song6ch3loop

@song6ch4:
@song6ch4loop:
@ref238:
	.byte $f9,$85
@ref239:
	.byte $f9,$85
	.byte $fd
	.word @song6ch4loop


@song7ch0:
	.byte $fb,$03
@song7ch0loop:
@ref240:
	.byte $a5,$8a,$32,$3a,$32,$3a,$40,$3c,$36,$3e,$36,$3e,$48,$48,$3c,$3a
	.byte $32,$bb
@ref241:
	.byte $92,$58,$f9,$83
@ref242:
	.byte $90,$52,$85,$01,$55,$58,$89,$01,$6a,$89,$01,$62,$89,$01,$67,$01
	.byte $62,$95,$00,$9d
	.byte $fd
	.word @song7ch0loop

@song7ch1:
@song7ch1loop:
@ref243:
	.byte $f9,$85
	.byte $ff,$19
	.word @ref233
	.byte $ff,$21
	.word @ref198
	.byte $fd
	.word @song7ch1loop

@song7ch2:
@song7ch2loop:
	.byte $ff,$12
	.word @ref206
@ref247:
	.byte $f9,$85
	.byte $ff,$12
	.word @ref207
	.byte $fd
	.word @song7ch2loop

@song7ch3:
@song7ch3loop:
	.byte $ff,$21
	.word @ref214
	.byte $ff,$19
	.word @ref237
	.byte $ff,$21
	.word @ref214
	.byte $fd
	.word @song7ch3loop

@song7ch4:
@song7ch4loop:
@ref252:
	.byte $f9,$85
@ref253:
	.byte $f9,$85
@ref254:
	.byte $f9,$85
	.byte $fd
	.word @song7ch4loop


@song8ch0:
	.byte $fb,$05
@song8ch0loop:
	.byte $ff,$13
	.word @ref190
	.byte $ff,$13
	.word @ref13
	.byte $ff,$18
	.word @ref14
	.byte $ff,$13
	.word @ref15
	.byte $ff,$13
	.word @ref194
	.byte $ff,$13
	.word @ref195
	.byte $ff,$18
	.word @ref196
	.byte $ff,$13
	.word @ref197
	.byte $fd
	.word @song8ch0loop

@song8ch1:
@song8ch1loop:
	.byte $ff,$21
	.word @ref198
	.byte $ff,$21
	.word @ref199
	.byte $ff,$21
	.word @ref199
	.byte $ff,$21
	.word @ref199
	.byte $ff,$21
	.word @ref199
	.byte $ff,$20
	.word @ref203
	.byte $ff,$21
	.word @ref199
	.byte $ff,$21
	.word @ref199
	.byte $fd
	.word @song8ch1loop

@song8ch2:
@song8ch2loop:
	.byte $ff,$12
	.word @ref206
	.byte $ff,$12
	.word @ref207
	.byte $ff,$12
	.word @ref207
	.byte $ff,$12
	.word @ref207
	.byte $ff,$12
	.word @ref207
	.byte $ff,$12
	.word @ref207
	.byte $ff,$12
	.word @ref207
	.byte $ff,$12
	.word @ref207
	.byte $fd
	.word @song8ch2loop

@song8ch3:
@song8ch3loop:
	.byte $ff,$21
	.word @ref214
	.byte $ff,$21
	.word @ref215
	.byte $ff,$21
	.word @ref215
	.byte $ff,$21
	.word @ref215
	.byte $ff,$21
	.word @ref215
	.byte $ff,$21
	.word @ref215
	.byte $ff,$21
	.word @ref215
	.byte $ff,$21
	.word @ref215
	.byte $fd
	.word @song8ch3loop

@song8ch4:
@song8ch4loop:
@ref287:
	.byte $f9,$85
@ref288:
	.byte $f9,$85
@ref289:
	.byte $f9,$85
@ref290:
	.byte $f9,$85
@ref291:
	.byte $f9,$85
@ref292:
	.byte $f9,$85
@ref293:
	.byte $f9,$85
@ref294:
	.byte $f9,$85
	.byte $fd
	.word @song8ch4loop


@song9ch0:
	.byte $fb,$08
@song9ch0loop:
@ref295:
	.byte $86,$1a,$1a,$22,$28,$41,$3b,$1e,$1e,$26,$2c,$45,$3f,$22,$22,$2a
	.byte $30,$49,$43,$40,$3c,$3a,$36,$33,$00,$c1
	.byte $fd
	.word @song9ch0loop

@song9ch1:
@song9ch1loop:
@ref296:
	.byte $90,$02,$02,$0a,$10,$29,$23,$06,$06,$0e,$14,$2d,$27,$0a,$0a,$12
	.byte $18,$31,$2b,$28,$24,$22,$1e,$1b,$00,$c1
	.byte $fd
	.word @song9ch1loop

@song9ch2:
@song9ch2loop:
@ref297:
	.byte $f9,$85
	.byte $fd
	.word @song9ch2loop

@song9ch3:
@song9ch3loop:
@ref298:
	.byte $a6,$08,$08,$09,$10,$85,$08,$08,$09,$10,$85,$08,$08,$09,$10,$85
	.byte $12,$12,$10,$10,$09,$00,$c1
	.byte $fd
	.word @song9ch3loop

@song9ch4:
@song9ch4loop:
@ref299:
	.byte $f9,$85
	.byte $fd
	.word @song9ch4loop


@song10ch0:
	.byte $fb,$03
@song10ch0loop:
@ref300:
	.byte $00,$f9,$83
@ref301:
	.byte $00,$f9,$83
@ref302:
	.byte $00,$f9,$83
@ref303:
	.byte $00,$f9,$83
@ref304:
	.byte $90,$4a,$85,$52,$85,$50,$85,$52,$85,$58,$85,$52,$85,$50,$85,$52
	.byte $85,$4a,$85,$52,$85,$50,$85,$52,$85,$58,$85,$52,$85,$50,$85,$52
	.byte $85
@ref305:
	.byte $4a,$85,$52,$85,$50,$85,$52,$85,$58,$85,$52,$85,$50,$85,$52,$85
	.byte $4a,$85,$52,$85,$50,$85,$52,$85,$58,$85,$52,$85,$50,$85,$52,$85
@ref306:
	.byte $52,$85,$58,$85,$56,$85,$58,$85,$60,$85,$58,$85,$56,$85,$58,$85
	.byte $52,$85,$58,$85,$56,$85,$58,$85,$60,$85,$58,$85,$56,$85,$58,$85
	.byte $ff,$20
	.word @ref306
	.byte $ff,$20
	.word @ref305
	.byte $ff,$20
	.word @ref305
	.byte $ff,$20
	.word @ref306
	.byte $ff,$20
	.word @ref306
	.byte $fd
	.word @song10ch0loop

@song10ch1:
@song10ch1loop:
@ref312:
	.byte $84,$03,$01,$03,$00,$a1,$03,$01,$03,$00,$a1,$06,$8d,$00,$8d
@ref313:
	.byte $03,$01,$03,$00,$a1,$03,$01,$03,$00,$a1,$06,$8d,$00,$8d
@ref314:
	.byte $0b,$01,$0b,$00,$a1,$0b,$01,$0b,$00,$a1,$10,$8d,$00,$8d
	.byte $ff,$0e
	.word @ref314
	.byte $ff,$0e
	.word @ref313
	.byte $ff,$0e
	.word @ref313
	.byte $ff,$0e
	.word @ref314
	.byte $ff,$0e
	.word @ref314
	.byte $ff,$0e
	.word @ref313
	.byte $ff,$0e
	.word @ref313
	.byte $ff,$0e
	.word @ref314
	.byte $ff,$0e
	.word @ref314
	.byte $fd
	.word @song10ch1loop

@song10ch2:
@song10ch2loop:
@ref324:
	.byte $00,$f9,$83
@ref325:
	.byte $00,$f9,$83
@ref326:
	.byte $00,$f9,$83
@ref327:
	.byte $00,$f9,$83
@ref328:
	.byte $98,$4a,$85,$52,$85,$50,$85,$52,$85,$58,$85,$52,$85,$50,$85,$52
	.byte $85,$4a,$85,$52,$85,$50,$85,$52,$85,$58,$85,$52,$85,$50,$85,$52
	.byte $85
	.byte $ff,$20
	.word @ref305
	.byte $ff,$20
	.word @ref306
	.byte $ff,$20
	.word @ref306
	.byte $ff,$20
	.word @ref305
	.byte $ff,$20
	.word @ref305
	.byte $ff,$20
	.word @ref306
	.byte $ff,$20
	.word @ref306
	.byte $fd
	.word @song10ch2loop

@song10ch3:
@song10ch3loop:
@ref336:
	.byte $84,$21,$00,$89,$21,$00,$89,$05,$00,$89,$21,$01,$21,$00,$a1,$05
	.byte $00,$99
@ref337:
	.byte $21,$00,$89,$21,$00,$89,$05,$00,$89,$21,$01,$21,$00,$a1,$05,$00
	.byte $99
@ref338:
	.byte $03,$00,$89,$03,$00,$89,$07,$00,$89,$03,$01,$03,$00,$a1,$07,$00
	.byte $99
	.byte $ff,$11
	.word @ref338
	.byte $ff,$11
	.word @ref337
	.byte $ff,$11
	.word @ref337
	.byte $ff,$11
	.word @ref338
	.byte $ff,$11
	.word @ref338
	.byte $ff,$11
	.word @ref337
	.byte $ff,$11
	.word @ref337
	.byte $ff,$11
	.word @ref338
	.byte $ff,$11
	.word @ref338
	.byte $fd
	.word @song10ch3loop

@song10ch4:
@song10ch4loop:
@ref348:
	.byte $f9,$85
@ref349:
	.byte $f9,$85
@ref350:
	.byte $f9,$85
@ref351:
	.byte $f9,$85
@ref352:
	.byte $f9,$85
@ref353:
	.byte $f9,$85
@ref354:
	.byte $f9,$85
@ref355:
	.byte $f9,$85
@ref356:
	.byte $f9,$85
@ref357:
	.byte $f9,$85
@ref358:
	.byte $f9,$85
@ref359:
	.byte $f9,$85
	.byte $fd
	.word @song10ch4loop


@song11ch0:
	.byte $fb,$08
@song11ch0loop:
@ref360:
	.byte $aa,$4b,$4e,$52,$83,$58,$83,$58,$83,$5d,$58,$91,$4b,$4e,$52,$83
	.byte $58,$83,$5c,$83,$61,$5c,$91,$4b,$4e,$52,$83,$58,$83,$58,$83,$55
	.byte $52,$81
@ref361:
	.byte $83,$4f,$4a,$83,$00,$4b,$4e,$52,$83,$58,$83,$52,$83,$4f,$4a,$93
	.byte $fd
	.word @song11ch0loop

@song11ch1:
@song11ch1loop:
@ref362:
	.byte $81,$aa,$4b,$4e,$52,$83,$58,$83,$58,$83,$5d,$58,$91,$4b,$4e,$52
	.byte $83,$58,$83,$5c,$83,$61,$5c,$91,$4b,$4e,$52,$83,$58,$83,$58,$83
	.byte $55,$52
@ref363:
	.byte $85,$4f,$4a,$83,$00,$4b,$4e,$52,$83,$58,$83,$52,$83,$4f,$4a,$91
	.byte $fd
	.word @song11ch1loop

@song11ch2:
@song11ch2loop:
@ref364:
	.byte $9e,$17,$1a,$1e,$83,$24,$83,$24,$83,$29,$24,$89,$00,$85,$17,$1a
	.byte $1e,$83,$24,$83,$28,$83,$2d,$28,$89,$00,$85,$17,$1a,$1e,$83,$24
	.byte $83,$24,$83,$21,$1e,$81
@ref365:
	.byte $83,$19,$14,$83,$00,$15,$18,$1c,$83,$22,$83,$1c,$83,$19,$14,$89
	.byte $0a,$02,$85
	.byte $fd
	.word @song11ch2loop

@song11ch3:
@song11ch3loop:
@ref366:
	.byte $ae,$20,$83,$04,$83,$20,$20,$20,$20,$83,$04,$04,$08,$08,$87,$08
	.byte $08,$83,$20,$83,$04,$83,$20,$20,$20,$20,$83,$04,$04,$08,$08,$87
	.byte $08,$08,$83,$20,$83,$04,$83,$20,$20,$20,$20,$83,$04,$04,$08,$08
@ref367:
	.byte $83,$04,$04,$08,$08,$83,$20,$83,$04,$83,$20,$20,$20,$20,$83,$04
	.byte $04,$08,$08,$87,$08,$08,$85
	.byte $fd
	.word @song11ch3loop

@song11ch4:
@song11ch4loop:
@ref368:
	.byte $f9,$85
@ref369:
	.byte $c1
	.byte $fd
	.word @song11ch4loop


@song12ch0:
	.byte $fb,$06
@ref370:
	.byte $00,$f9,$83
@song12ch0loop:
@ref371:
	.byte $f9,$85
	.byte $fd
	.word @song12ch0loop

@song12ch1:
@ref372:
	.byte $00,$f9,$83
@song12ch1loop:
@ref373:
	.byte $ac,$02,$83,$02,$b7,$02,$83,$02,$b7
	.byte $fd
	.word @song12ch1loop

@song12ch2:
@ref374:
	.byte $a2,$18,$16,$14,$12,$10,$0e,$0c,$0a,$08,$06,$04,$02,$e7
@song12ch2loop:
@ref375:
	.byte $f9,$85
	.byte $fd
	.word @song12ch2loop

@song12ch3:
@ref376:
	.byte $00,$95,$96,$04,$00,$83,$1c,$9d,$00,$bd
@song12ch3loop:
@ref377:
	.byte $f9,$85
	.byte $fd
	.word @song12ch3loop

@song12ch4:
@ref378:
	.byte $f9,$85
@song12ch4loop:
@ref379:
	.byte $f9,$85
	.byte $fd
	.word @song12ch4loop


@song13ch0:
	.byte $fb,$04
@song13ch0loop:
@ref380:
	.byte $8e,$32,$95,$3a,$85,$40,$95,$44,$85
@ref381:
	.byte $48,$95,$44,$85,$40,$9d
@ref382:
	.byte $00,$bd
@ref383:
	.byte $22,$85,$28,$85,$30,$85,$22,$85,$28,$85,$30,$85,$22,$85,$28,$85
@ref384:
	.byte $30,$85,$22,$85,$28,$85,$30,$85,$1e,$85,$24,$85,$2c,$85,$1e,$85
@ref385:
	.byte $24,$85,$2c,$85,$1e,$85,$24,$85,$2c,$85,$1e,$85,$24,$85,$2c,$85
	.byte $ff,$10
	.word @ref383
@ref387:
	.byte $30,$85,$22,$85,$28,$85,$30,$85,$24,$85,$2c,$85,$32,$85,$24,$85
@ref388:
	.byte $2c,$85,$32,$85,$24,$85,$2c,$85,$32,$85,$24,$85,$2c,$85,$32,$85
@ref389:
	.byte $22,$8d,$00,$ad
	.byte $fd
	.word @song13ch0loop

@song13ch1:
@song13ch1loop:
@ref390:
	.byte $81,$88,$1a,$95,$22,$85,$28,$95,$2c,$83
@ref391:
	.byte $81,$30,$95,$2c,$85,$28,$9b
@ref392:
	.byte $00,$bd
@ref393:
	.byte $8e,$3a,$95,$3a,$95,$3a,$8d
@ref394:
	.byte $87,$3a,$95,$36,$95,$36,$85
@ref395:
	.byte $8f,$36,$95,$36,$95
@ref396:
	.byte $3a,$95,$3a,$95,$3a,$8d
@ref397:
	.byte $87,$3a,$95,$3c,$95,$3c,$85
@ref398:
	.byte $8f,$3c,$95,$3c,$95
@ref399:
	.byte $3a,$8d,$00,$ad
	.byte $fd
	.word @song13ch1loop

@song13ch2:
@song13ch2loop:
@ref400:
	.byte $bf
@ref401:
	.byte $bf
@ref402:
	.byte $bf
@ref403:
	.byte $bf
@ref404:
	.byte $bf
@ref405:
	.byte $bf
@ref406:
	.byte $bf
@ref407:
	.byte $bf
@ref408:
	.byte $bf
@ref409:
	.byte $8f,$00,$ad
	.byte $fd
	.word @song13ch2loop

@song13ch3:
@song13ch3loop:
@ref410:
	.byte $bf
@ref411:
	.byte $bf
@ref412:
	.byte $88,$02,$07,$00,$b7
@ref413:
	.byte $bf
@ref414:
	.byte $bf
@ref415:
	.byte $bf
@ref416:
	.byte $bf
@ref417:
	.byte $bf
@ref418:
	.byte $bf
@ref419:
	.byte $8f,$00,$ad
	.byte $fd
	.word @song13ch3loop

@song13ch4:
@song13ch4loop:
@ref420:
	.byte $bf
@ref421:
	.byte $bf
@ref422:
	.byte $bf
@ref423:
	.byte $bf
@ref424:
	.byte $bf
@ref425:
	.byte $bf
@ref426:
	.byte $bf
@ref427:
	.byte $bf
@ref428:
	.byte $bf
@ref429:
	.byte $bf
	.byte $fd
	.word @song13ch4loop


@song14ch0:
	.byte $fb,$04
@song14ch0loop:
@ref430:
	.byte $90,$4a,$8d,$00,$85,$5c,$85,$58,$85,$54,$85,$00,$8d
@ref431:
	.byte $4a,$8d,$00,$85,$5c,$85,$58,$85,$54,$85,$00,$8d
	.byte $ff,$0c
	.word @ref431
@ref433:
	.byte $52,$85,$00,$85,$54,$85,$00,$85,$58,$85,$00,$95
	.byte $ff,$0c
	.word @ref431
	.byte $ff,$0c
	.word @ref431
	.byte $ff,$0c
	.word @ref431
@ref437:
	.byte $4e,$85,$00,$85,$52,$85,$00,$85,$54,$85,$00,$95
	.byte $fd
	.word @song14ch0loop

@song14ch1:
@song14ch1loop:
@ref438:
	.byte $b4,$02,$8d,$00,$85,$14,$85,$10,$85,$0c,$85,$00,$8d
@ref439:
	.byte $02,$8d,$00,$85,$14,$85,$10,$85,$0c,$85,$00,$8d
	.byte $ff,$0c
	.word @ref439
@ref441:
	.byte $0a,$85,$00,$85,$0c,$85,$00,$85,$10,$85,$00,$95
	.byte $ff,$0c
	.word @ref439
	.byte $ff,$0c
	.word @ref439
	.byte $ff,$0c
	.word @ref439
@ref445:
	.byte $06,$85,$00,$85,$0a,$85,$00,$85,$0c,$85,$00,$95
	.byte $fd
	.word @song14ch1loop

@song14ch2:
@song14ch2loop:
@ref446:
	.byte $bf
@ref447:
	.byte $bf
@ref448:
	.byte $bf
@ref449:
	.byte $bf
@ref450:
	.byte $bf
@ref451:
	.byte $bf
@ref452:
	.byte $bf
@ref453:
	.byte $bf
	.byte $fd
	.word @song14ch2loop

@song14ch3:
@song14ch3loop:
@ref454:
	.byte $bf
@ref455:
	.byte $bf
@ref456:
	.byte $bf
@ref457:
	.byte $bf
@ref458:
	.byte $bf
@ref459:
	.byte $bf
@ref460:
	.byte $bf
@ref461:
	.byte $bf
	.byte $fd
	.word @song14ch3loop

@song14ch4:
@song14ch4loop:
@ref462:
	.byte $bf
@ref463:
	.byte $bf
@ref464:
	.byte $bf
@ref465:
	.byte $bf
@ref466:
	.byte $bf
@ref467:
	.byte $bf
@ref468:
	.byte $bf
@ref469:
	.byte $bf
	.byte $fd
	.word @song14ch4loop
