;this file for FamiTone2 libary generated by nsf2data tool

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_0
	.word @sfx_ntsc_1
	.word @sfx_ntsc_2

@sfx_ntsc_0:
	.byte $89,$38,$8a,$08,$01,$8a,$09,$01,$8a,$02,$01,$8a,$00,$01,$8a,$05
	.byte $01,$8a,$02,$07,$00
@sfx_ntsc_1:
	.byte $80,$3f,$81,$69,$82,$00,$86,$81,$87,$b8,$88,$00,$01,$81,$73,$87
	.byte $f4,$01,$87,$43,$88,$01,$01,$87,$73,$03,$81,$5e,$87,$46,$01,$81
	.byte $68,$87,$82,$01,$87,$d1,$01,$87,$01,$88,$02,$09,$00
@sfx_ntsc_2:
	.byte $80,$3b,$81,$7e,$82,$00,$01,$81,$77,$01,$81,$70,$01,$81,$6a,$09
	.byte $00
