;this file for FamiTone2 libary generated by nsf2data tool

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_0
	.word @sfx_ntsc_1

@sfx_ntsc_0:
	.byte $89,$38,$8a,$08,$01,$8a,$09,$01,$8a,$02,$01,$8a,$00,$01,$8a,$05
	.byte $01,$8a,$02,$07,$00
@sfx_ntsc_1:
	.byte $80,$3f,$81,$69,$82,$00,$86,$81,$87,$69,$88,$00,$01,$81,$73,$87
	.byte $73,$05,$81,$5e,$87,$5e,$01,$81,$68,$87,$68,$0b,$00
