; Definitions for all sprites used by our app, and some useful constants.

SPRITE_TYPE_COLLECTIBLE 		= 0
SPRITE_TYPE_JUMPABLE_ENEMY		= 1
SPRITE_TYPE_INVULN_ENEMY		= 2
SPRITE_TYPE_DIMENSIONER			= 3

SPRITE_SIZE_DEFAULT					= 0
SPRITE_SIZE_TINY					= 1
SPRITE_SIZE_2X1						= 2
SPRITE_SIZE_3X1						= 3
SPRITE_SIZE_4X1						= 4
SPRITE_SIZE_TINY_NORMAL_ALIGNMENT 	= 5

SPRITE_ANIMATION_NONE 			= 0
SPRITE_ANIMATION_NORMAL			= 1
SPRITE_ANIMATION_BINARY			= 2 ; first tile, second tile, first tile, second tile...
SPRITE_ANIMATION_DYING			= $a0

SPRITE_TYPE_COIN 		= 0
SPRITE_TYPE_TURTLE		= 1
SPRITE_TYPE_GATOR		= 2
SPRITE_TYPE_SNAKE		= 3
SPRITE_TYPE_PLATFORM	= 4

PALETTE_0				= %00000000
PALETTE_1				= %00000001
PALETTE_2				= %00000010
PALETTE_3				= %00000011

COLLECTIBLE_SPRITE_ID	= 0

sprite_definitions: 
	; Type, width, height, size, animation, first tile id, palette, speed.
	.byte SPRITE_TYPE_COLLECTIBLE, 8, 8, SPRITE_SIZE_TINY, SPRITE_ANIMATION_NONE, $2, PALETTE_0, 0		; 0. Coin
	.byte SPRITE_TYPE_JUMPABLE_ENEMY, 16, 8, SPRITE_SIZE_2X1, SPRITE_ANIMATION_NORMAL, $20, PALETTE_1, 1 		; 1. Turtle
	.byte SPRITE_TYPE_JUMPABLE_ENEMY, 16, 8, SPRITE_SIZE_2X1, SPRITE_ANIMATION_NORMAL, $24, PALETTE_1, 1		; 2. Gator
	.byte SPRITE_TYPE_JUMPABLE_ENEMY, 24, 8, SPRITE_SIZE_3X1, SPRITE_ANIMATION_NORMAL, $28, PALETTE_1, 2		; 3. Snake
	.byte SPRITE_TYPE_INVULN_ENEMY, 16, 14, SPRITE_SIZE_DEFAULT, SPRITE_ANIMATION_NORMAL, $40, PALETTE_1, 1	; 4. Militarized turtle
	.byte SPRITE_TYPE_PLATFORM, 32, 8, SPRITE_SIZE_4X1, SPRITE_ANIMATION_NORMAL, $03, PALETTE_1, 0 ; Falling platform.
	.byte 0, 0, 0, 0, 0, 0, 0, 0
	.byte 0, 0, 0, 0, 0, 0, 0, 0 ; Blank sprites to keep dimension stuff on one line.

; Dimension Swappers
	.byte SPRITE_TYPE_DIMENSIONER, 32, 16, SPRITE_SIZE_TINY_NORMAL_ALIGNMENT, SPRITE_ANIMATION_NONE, $cf, DIMENSION_PLAIN, DIMENSION_BARREN
	.byte SPRITE_TYPE_DIMENSIONER, 32, 16, SPRITE_SIZE_TINY_NORMAL_ALIGNMENT, SPRITE_ANIMATION_NONE, $cf, DIMENSION_PLAIN, DIMENSION_ICE_AGE
	.byte SPRITE_TYPE_DIMENSIONER, 32, 16, SPRITE_SIZE_TINY_NORMAL_ALIGNMENT, SPRITE_ANIMATION_NONE, $cf, DIMENSION_ICE_AGE, DIMENSION_BARREN
	.byte SPRITE_TYPE_DIMENSIONER, 32, 16, SPRITE_SIZE_TINY_NORMAL_ALIGNMENT, SPRITE_ANIMATION_NONE, $cf, DIMENSION_AGGRESSIVE, DIMENSION_PLAIN



DIMENSION_PLAIN_TO_CALM = 8
; DIMENSION_WHATEVER = DIMENSION_PLAIN_TO_CALM+1