; Definitions for all sprites used by our app, and some useful constants.

SPRITE_TYPE_COLLECTIBLE 		= 0
SPRITE_TYPE_JUMPABLE_ENEMY		= 1
SPRITE_TYPE_INVULN_ENEMY		= 2

SPRITE_SIZE_DEFAULT		= 0
SPRITE_SIZE_TINY		= 1
SPRITE_SIZE_2X1			= 2
SPRITE_SIZE_3X1			= 3

SPRITE_ANIMATION_NONE 			= 0
SPRITE_ANIMATION_NORMAL			= 1
SPRITE_ANIMATION_BINARY			= 2 ; first tile, second tile, first tile, second tile...

SPRITE_TYPE_COIN 		= 0
SPRITE_TYPE_TURTLE		= 1
SPRITE_TYPE_GATOR		= 2
SPRITE_TYPE_SNAKE		= 3

PALETTE_0				= %00000000
PALETTE_1				= %00000001
PALETTE_2				= %00000010
PALETTE_3				= %00000011

sprite_definitions: 
	; Type, size, animation, first tile id.
	.byte SPRITE_TYPE_COLLECTIBLE, SPRITE_SIZE_TINY, SPRITE_ANIMATION_NONE, $0, PALETTE_0, $0, $0, $0		; 0. Coin
	.byte SPRITE_TYPE_JUMPABLE_ENEMY, SPRITE_SIZE_2X1, SPRITE_ANIMATION_NORMAL, $20, PALETTE_1, $0, $0, $0 	; 1. Turtle
	.byte SPRITE_TYPE_INVULN_ENEMY, SPRITE_SIZE_2X1, SPRITE_ANIMATION_NORMAL, $24, PALETTE_1, $0, $0, $0		; 2. Gator
	.byte SPRITE_TYPE_JUMPABLE_ENEMY, SPRITE_SIZE_3X1, SPRITE_ANIMATION_NORMAL, $2d, PALETTE_1, $0, $0, $0	; 3. Snake
